# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'app/controllers/**/*.rb'
    - 'app/services/**/*.rb'
  Max: 30  # Controllers tend to be a bit longer in API apps

Metrics/MethodLength:
  Max: 15 
  
### Exclude files from Rubocop for faster linting
AllCops:
  Exclude:
    - 'app/serializers/**/*'
    - 'app/docs/**/*'
    - 'app/swagger/**/*'
    - 'db/schema.rb'
    - 'spec/**/*'
