ARG RUBY_VERSION=3.2.3
FROM ruby:$RUBY_VERSION-slim

# Install required packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev curl libvips \
    postgresql-client nodejs npm && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Rails app lives here
WORKDIR /rails

# Set development environment
ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle

# Copy application code
COPY Gemfile Gemfile.lock ./

# Install gems
RUN bundle config set --local without 'production' && \
    bundle install --jobs 4 --retry 3

# Copy the rest of the application code
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the Rails server
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"] 